In [89]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.gaussian_process import GaussianProcessRegressor

In [90]:
X1 = np.load(r'C:\Users\xdb13122\Desktop\ML Course\capstone project\initial_data\function_6\initial_inputs.npy')
Y1 = np.load(r'C:\Users\xdb13122\Desktop\ML Course\capstone project\initial_data\function_6\initial_outputs.npy')
X2 = np.load(r'C:\Users\xdb13122\Desktop\ML Course\capstone project\initial_data2\function_6\initial_inputs.npy')
Y2 = np.load(r'C:\Users\xdb13122\Desktop\ML Course\capstone project\initial_data2\function_6\initial_outputs.npy')
X = np.concatenate((X1, X2), axis=0)
Y = np.concatenate((Y1, Y2), axis=0)

In [91]:
X

array([[7.28186105e-01, 1.54692570e-01, 7.32551669e-01, 6.93996509e-01,
        5.64013105e-02],
       [2.42384347e-01, 8.44099972e-01, 5.77809099e-01, 6.79021284e-01,
        5.01952888e-01],
       [7.29522610e-01, 7.48106200e-01, 6.79774641e-01, 3.56552279e-01,
        6.71053683e-01],
       [7.70620242e-01, 1.14403744e-01, 4.67799319e-02, 6.48324285e-01,
        2.73549053e-01],
       [6.18812299e-01, 3.31802137e-01, 1.87287868e-01, 7.56238474e-01,
        3.28834798e-01],
       [7.84958094e-01, 9.10682349e-01, 7.08120104e-01, 9.59225429e-01,
        4.91149586e-03],
       [1.45110786e-01, 8.96684598e-01, 8.96322235e-01, 7.26271537e-01,
        2.36271991e-01],
       [9.45069068e-01, 2.88459051e-01, 9.78805764e-01, 9.61655587e-01,
        5.98015936e-01],
       [1.25720155e-01, 8.62724692e-01, 2.85443322e-02, 2.46605272e-01,
        7.51206241e-01],
       [7.57594355e-01, 3.55831415e-01, 1.65228997e-02, 4.34207205e-01,
        1.12433044e-01],
       [5.36796903e-01, 3.0878

In [92]:
new_row = np.array([[0.977718, 0.138594, 0.867264, 0.284583, 0.112673], [0.920995, 0.03783 , 0.48097 , 0.58218 , 0.724458], [0.268528, 0.232648, 0.284285, 0.905266, 0.786491],[0.268528, 0.232648, 0.284285, 0.905266, 0.786491], [0.578296, 0.730171, 0.818198, 0.493648, 0.840202], [0.515191, 0.187116, 0.55999 , 0.893004, 0.45831]])
X = np.concatenate((X, new_row), axis=0)

In [93]:
X

array([[7.28186105e-01, 1.54692570e-01, 7.32551669e-01, 6.93996509e-01,
        5.64013105e-02],
       [2.42384347e-01, 8.44099972e-01, 5.77809099e-01, 6.79021284e-01,
        5.01952888e-01],
       [7.29522610e-01, 7.48106200e-01, 6.79774641e-01, 3.56552279e-01,
        6.71053683e-01],
       [7.70620242e-01, 1.14403744e-01, 4.67799319e-02, 6.48324285e-01,
        2.73549053e-01],
       [6.18812299e-01, 3.31802137e-01, 1.87287868e-01, 7.56238474e-01,
        3.28834798e-01],
       [7.84958094e-01, 9.10682349e-01, 7.08120104e-01, 9.59225429e-01,
        4.91149586e-03],
       [1.45110786e-01, 8.96684598e-01, 8.96322235e-01, 7.26271537e-01,
        2.36271991e-01],
       [9.45069068e-01, 2.88459051e-01, 9.78805764e-01, 9.61655587e-01,
        5.98015936e-01],
       [1.25720155e-01, 8.62724692e-01, 2.85443322e-02, 2.46605272e-01,
        7.51206241e-01],
       [7.57594355e-01, 3.55831415e-01, 1.65228997e-02, 4.34207205e-01,
        1.12433044e-01],
       [5.36796903e-01, 3.0878

In [94]:
Y

array([-0.71426495, -1.20995524, -1.67219994, -1.53605771, -0.82923655,
       -1.24704893, -1.23378638, -1.69434344, -2.57116963, -1.30911635,
       -1.14478485, -1.91267714, -1.62283895, -1.35668211, -2.0184254 ,
       -1.70255784, -1.29424696, -0.93575656, -2.15576776, -1.74688209,
       -1.51269542, -1.34959856, -1.82739562, -1.71602331, -0.97248425,
       -1.20521138, -1.10099104, -1.91309535, -1.05157417, -1.19458833,
       -2.06906505, -1.48937327, -1.82528398, -1.7476171 , -1.35823203,
       -1.44913772, -1.81134837, -2.00771782, -0.99967761, -1.67533648])

In [95]:
new_row = np.array([-1.431987070285614,  -1.8041381484255152, -1.4224869897156354, -1.5272868582803165, -1.6867407199659736, -0.9222380101975867])
Y = np.concatenate((Y, new_row), axis=0)

In [96]:
Y

array([-0.71426495, -1.20995524, -1.67219994, -1.53605771, -0.82923655,
       -1.24704893, -1.23378638, -1.69434344, -2.57116963, -1.30911635,
       -1.14478485, -1.91267714, -1.62283895, -1.35668211, -2.0184254 ,
       -1.70255784, -1.29424696, -0.93575656, -2.15576776, -1.74688209,
       -1.51269542, -1.34959856, -1.82739562, -1.71602331, -0.97248425,
       -1.20521138, -1.10099104, -1.91309535, -1.05157417, -1.19458833,
       -2.06906505, -1.48937327, -1.82528398, -1.7476171 , -1.35823203,
       -1.44913772, -1.81134837, -2.00771782, -0.99967761, -1.67533648,
       -1.43198707, -1.80413815, -1.42248699, -1.52728686, -1.68674072,
       -0.92223801])

In [97]:
import numpy as np
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern
from scipy.optimize import minimize
from scipy.stats import norm  # Importing norm from scipy.stats for the acquisition function
from sklearn.preprocessing import StandardScaler
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern
# Initial data
X = X
y = Y
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
# Define the Gaussian Process model with Matern kernel (suitable for noisy functions)
kernel = Matern(nu=2.5)
gp = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=10, alpha=1e-6, optimizer="fmin_l_bfgs_b")

# Fit the GP model to the initial data
gp.fit(X_scaled, y)

# Define the acquisition function (Expected Improvement)
def acquisition_function(x, gp, y_min):
    mean, std = gp.predict(x.reshape(1, -1), return_std=True)
    std = std.reshape(-1, 1)
    z = (y_min - mean) / std
    return (y_min - mean) * norm.cdf(z) + std * norm.pdf(z)

# Optimization routine for selecting new points
n_iterations = 50
for i in range(n_iterations):
    # Minimum of observed values
    y_min = np.min(y)

    # Minimize the acquisition function to find the next best point
    x_next = minimize(lambda x: acquisition_function(x, gp, y_min), 
                      x0=np.random.rand(5), bounds=[(0, 1)]*5, 
                      method='L-BFGS-B').x

    # Predict the output using the Gaussian Process model for the new point
    y_next, _ = gp.predict(x_next.reshape(1, -1), return_std=True)

    # Append new point to data
    X = np.vstack((X, x_next))
    y = np.append(y, y_next)

    # Re-train the Gaussian Process model with the new data
    gp.fit(X, y)

# Result: the optimal ingredient combination to minimize the overall score
optimal_ingredients = X[np.argmin(y)]
optimal_score = np.min(y)

print("Optimal Ingredients:", optimal_ingredients)
print("Optimal Score:", optimal_score)


C:\Users\xdb13122\AppData\Local\anaconda3\Lib\site-packages\sklearn\gaussian_process\_gpr.py:659: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)
C:\Users\xdb13122\AppData\Local\anaconda3\Lib\site-packages\sklearn\gaussian_process\_gpr.py:659: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)


Optimal Ingredients: [0.12572016 0.86272469 0.02854433 0.24660527 0.75120624]
Optimal Score: -2.5711696316081234


C:\Users\xdb13122\AppData\Local\anaconda3\Lib\site-packages\sklearn\gaussian_process\_gpr.py:659: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)
