In [43]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.gaussian_process import GaussianProcessRegressor

In [44]:
X1 = np.load(r'C:\Users\xdb13122\Desktop\ML Course\capstone project\initial_data\function_3\initial_inputs.npy')
Y1 = np.load(r'C:\Users\xdb13122\Desktop\ML Course\capstone project\initial_data\function_3\initial_outputs.npy')
X2 = np.load(r'C:\Users\xdb13122\Desktop\ML Course\capstone project\initial_data2\function_3\initial_inputs.npy')
Y2 = np.load(r'C:\Users\xdb13122\Desktop\ML Course\capstone project\initial_data2\function_3\initial_outputs.npy')
X = np.concatenate((X1, X2), axis=0)
Y = np.concatenate((Y1, Y2), axis=0)

In [45]:
X

array([[0.17152521, 0.34391687, 0.2487372 ],
       [0.24211446, 0.64407427, 0.27243281],
       [0.53490572, 0.39850092, 0.17338873],
       [0.49258141, 0.61159319, 0.34017639],
       [0.13462167, 0.21991724, 0.45820622],
       [0.34552327, 0.94135983, 0.26936348],
       [0.15183663, 0.43999062, 0.99088187],
       [0.64550284, 0.39714294, 0.91977134],
       [0.74691195, 0.28419631, 0.22629985],
       [0.17047699, 0.6970324 , 0.14916943],
       [0.22054934, 0.29782524, 0.34355534],
       [0.66601366, 0.67198515, 0.2462953 ],
       [0.04680895, 0.23136024, 0.77061759],
       [0.60009728, 0.72513573, 0.06608864],
       [0.96599485, 0.86111969, 0.56682913],
       [0.16569979, 0.25685582, 0.65469   ],
       [0.65099632, 0.42417272, 0.52674437],
       [0.10601263, 0.24333177, 0.65025654],
       [0.35216426, 0.10580766, 0.06546785],
       [0.829086  , 0.4393692 , 0.20713429],
       [0.80489315, 0.31206954, 0.24371441],
       [0.46204056, 0.12939599, 0.83858636],
       [0.

In [46]:
new_row = np.array([[0.864411, 0.276113, 0.874451], [0.791462, 0.581073, 0.615003], [0.699532, 0.529816, 0.4750162],[0.699532, 0.529816, 0.475016], [0.788473, 0.982177, 0.253373], [0.228546, 0.599028, 0.31107]])
X = np.concatenate((X, new_row), axis=0)

In [47]:
X

array([[0.17152521, 0.34391687, 0.2487372 ],
       [0.24211446, 0.64407427, 0.27243281],
       [0.53490572, 0.39850092, 0.17338873],
       [0.49258141, 0.61159319, 0.34017639],
       [0.13462167, 0.21991724, 0.45820622],
       [0.34552327, 0.94135983, 0.26936348],
       [0.15183663, 0.43999062, 0.99088187],
       [0.64550284, 0.39714294, 0.91977134],
       [0.74691195, 0.28419631, 0.22629985],
       [0.17047699, 0.6970324 , 0.14916943],
       [0.22054934, 0.29782524, 0.34355534],
       [0.66601366, 0.67198515, 0.2462953 ],
       [0.04680895, 0.23136024, 0.77061759],
       [0.60009728, 0.72513573, 0.06608864],
       [0.96599485, 0.86111969, 0.56682913],
       [0.16569979, 0.25685582, 0.65469   ],
       [0.65099632, 0.42417272, 0.52674437],
       [0.10601263, 0.24333177, 0.65025654],
       [0.35216426, 0.10580766, 0.06546785],
       [0.829086  , 0.4393692 , 0.20713429],
       [0.80489315, 0.31206954, 0.24371441],
       [0.46204056, 0.12939599, 0.83858636],
       [0.

In [48]:
Y

array([-0.1121222 , -0.08796286, -0.11141465, -0.03483531, -0.04800758,
       -0.11062091, -0.39892551, -0.11386851, -0.13146061, -0.09418956,
       -0.04694741, -0.10596504, -0.11804826, -0.03637783, -0.05675837,
       -0.12809391, -0.03103939, -0.1172756 , -0.07944403, -0.14258557,
       -0.11962132, -0.06119926, -0.03435924, -0.0876973 , -0.11502216,
       -0.07478879, -0.10441561, -0.08945485, -0.08760022, -0.02514614])

In [49]:
new_row = np.array([-0.05412569940370686, -0.06319905645357159, -0.0005480369123123483, -0.0005480369123123483, -0.16369976998517352, -0.07402727571803658])
Y = np.concatenate((Y, new_row), axis=0)

In [50]:
Y

array([-0.1121222 , -0.08796286, -0.11141465, -0.03483531, -0.04800758,
       -0.11062091, -0.39892551, -0.11386851, -0.13146061, -0.09418956,
       -0.04694741, -0.10596504, -0.11804826, -0.03637783, -0.05675837,
       -0.12809391, -0.03103939, -0.1172756 , -0.07944403, -0.14258557,
       -0.11962132, -0.06119926, -0.03435924, -0.0876973 , -0.11502216,
       -0.07478879, -0.10441561, -0.08945485, -0.08760022, -0.02514614,
       -0.0541257 , -0.06319906, -0.00054804, -0.00054804, -0.16369977,
       -0.07402728])

In [51]:
# Random search around an area restricted around $x$ = [0.57771284, 0.77197318]
next_query_x1 = np.random.normal(0.57771284, scale = 0.01)
next_query_x2 = np.random.normal(0.77197318, scale = 0.01)
next_query_x3 = np.random.normal(0.77197318, scale = 0.01)
print('Next query Random: ', [next_query_x1, next_query_x2, next_query_x3])

# Using a restricted UCB
gpr = GaussianProcessRegressor()
gpr.fit(X, Y)
# to optimize the acquisition function, we will simply use gridsearch over a space of 10.000 gridpoints
x1 = np.linspace(0, 1, 100)
x2 = np.linspace(0, 1, 100)
x3 = np.linspace(0, 1, 100)
X_grid = []
for i in range(len(x1)):
    for j in range(len(x2)):
        for k in range(len(x2)):
            X_grid.append([x1[i], x2[j], x3[k]])

X_grid = np.array(X_grid)
mean, std = gpr.predict(X_grid, return_std = True)
ucb = mean + 1.96 * std

idx_max = np.argmax(ucb)
next_query = X_grid[idx_max]
print(next_query)

Next query Random:  [0.5758351169093209, 0.7556730262590177, 0.7812975256644945]
[1. 0. 1.]


In [54]:
import numpy as np
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C
from skopt import gp_minimize
from skopt.space import Real
from skopt.utils import use_named_args

# Define the input and output data
X = X
Y = Y

# Define the kernel and Gaussian Process with noise tolerance
kernel = C(1.0, (1e-4, 1e4)) * RBF(length_scale=1.0, length_scale_bounds=(1e-3, 1e3))
gp = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=10, alpha=0.1)
gp.fit(X, Y)

# Define the search space for the three variables (Real values based on range in X)
space = [
    Real(X[:, 0].min(), X[:, 0].max(), name="x1"),
    Real(X[:, 1].min(), X[:, 1].max(), name="x2"),
    Real(X[:, 2].min(), X[:, 2].max(), name="x3")
]

# Define the objective function to minimize |adverse reaction| (bring it close to zero)
@use_named_args(space)
def objective(**params):
    x_pred = np.array([[params["x1"], params["x2"], params["x3"]]])
    y_pred, _ = gp.predict(x_pred, return_std=True)
    return abs(y_pred[0])  # Minimize the absolute value of the adverse reaction

# Run Bayesian Optimization to minimize the absolute value of the adverse reaction
result = gp_minimize(
    objective, space, n_calls=60, random_state=0, acq_func="EI", n_initial_points=5
)

# Extract the best parameters and minimum adverse reaction (closest to zero)
best_x1, best_x2, best_x3 = result.x
closest_to_zero_adverse_reaction = result.fun

print(f"Optimal values for minimizing adverse reaction:")
print(f"x1 = {best_x1}, x2 = {best_x2}, x3 = {best_x3}")
print(f"Minimum adverse reaction (closest to zero): {closest_to_zero_adverse_reaction}")

C:\Users\xdb13122\AppData\Local\anaconda3\Lib\site-packages\sklearn\gaussian_process\kernels.py:455: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__length_scale is close to the specified upper bound 1000.0. Increasing the bound and calling fit again may find a better value.
  warnings.warn(


Optimal values for minimizing adverse reaction:
x1 = 0.9794082576780888, x2 = 0.905247530768202, x3 = 0.5394771512229771
Minimum adverse reaction (closest to zero): 0.05993257949438238


In [ ]:
from sklearn.linear_model import LinearRegression
from skopt import gp_minimize
from skopt.space import Real
import numpy as np
import matplotlib.pyplot as plt

# Define the input and output data
X = X
Y = Y
# Step 1: Fit a linear regression model
linear_model = LinearRegression()
linear_model.fit(X, Y)

# Step 2: Define the objective function to minimize
def objective_function(x):
    x = np.array(x).reshape(1, -1)  # Reshape x to fit the model input shape
    y_pred = linear_model.predict(x)[0]  # Predict output using linear model
    return abs(y_pred)  # Use absolute value to bring prediction closer to zero

# Step 3: Use Bayesian optimization to find the optimal values of x1, x2, and x3
# Define the bounds for x1, x2, and x3 (based on observed ranges in the data)
space = [
    Real(0, 1, name='x1'),
    Real(0, 1, name='x2'),
    Real(0, 1, name='x3')
]

# Run Bayesian optimization
result = gp_minimize(objective_function, space, n_calls=50, random_state=0)

# Extract optimal values for x1, x2, x3 and the minimum objective function value
optimal_x1, optimal_x2, optimal_x3 = result.x
optimal_y = linear_model.predict([[optimal_x1, optimal_x2, optimal_x3]])[0]

print("Optimal x1:", optimal_x1)
print("Optimal x2:", optimal_x2)
print("Optimal x3:", optimal_x3)
print("Predicted Y for optimal x1, x2, x3:", optimal_y)

In [ ]:
# Plotting the convergence of the optimization process
plt.plot(result.func_vals, marker='o', linestyle='-', color='b')
plt.xlabel("Iteration")
plt.ylabel("Objective Function Value (|Y|)")
plt.title("Convergence of Bayesian Optimization for Linear Regression")
plt.grid(True)
plt.show()

In [ ]:
import matplotlib.pyplot as plt

# Create partial dependency plots for each variable
fig, axs = plt.subplots(1, 3, figsize=(18, 5))

# For each variable, fix the other two at their mean values
x_means = np.mean(X, axis=0)

for i in range(3):
    # Vary only the i-th variable over its observed range
    x_varied = np.linspace(X[:, i].min(), X[:, i].max(), 100)
    X_plot = np.tile(x_means, (100, 1))  # Start with all features at mean
    X_plot[:, i] = x_varied  # Vary only the i-th feature
    
    # Predict output for each value of the i-th variable
    Y_pred = linear_model.predict(X_plot)
    
    # Plot the relationship between the i-th variable and the prediction
    axs[i].plot(x_varied, Y_pred, label=f"Variable {i+1}")
    axs[i].set_xlabel(f"X{i+1}")
    axs[i].set_ylabel("Predicted Y")
    axs[i].set_title(f"Effect of Variable {i+1} on Y")
    axs[i].grid()

plt.tight_layout()
plt.show()

In [ ]:
from skopt import gp_minimize
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

# Define the input and output data
X = X
Y = Y
# Step 1: Fit the polynomial regression model
poly = PolynomialFeatures(degree=2, include_bias=False)
X_poly = poly.fit_transform(X)
poly_model = LinearRegression()
poly_model.fit(X_poly, Y)

# Step 2: Define the objective function to minimize (or bring to zero)
def objective_function(x):
    x_poly = poly.transform([x])  # Transform input x to polynomial features
    y_pred = poly_model.predict(x_poly)[0]  # Predict output using polynomial model
    return abs(y_pred)  # Use absolute value to bring prediction closer to zero

# Step 3: Use Bayesian optimization to find the optimal values of x1, x2, and x3
from skopt.space import Real

# Define the bounds for x1, x2, and x3 (based on observed ranges in the data)
space = [
    Real(0, 1, name='x1'),
    Real(0, 1, name='x2'),
    Real(0, 1, name='x3')
]

# Run Bayesian optimization
result = gp_minimize(objective_function, space, n_calls=50, random_state=0)

# Optimal values for x1, x2, x3 and the minimum objective function value
optimal_x1, optimal_x2, optimal_x3 = result.x
optimal_y = poly_model.predict(poly.transform([[optimal_x1, optimal_x2, optimal_x3]]))[0]

print("Optimal x1:", optimal_x1)
print("Optimal x2:", optimal_x2)
print("Optimal x3:", optimal_x3)
print("Predicted Y for optimal x1, x2, x3:", optimal_y)

In [ ]:
# Plotting the convergence of the optimization process
plt.plot(result.func_vals, marker='o', linestyle='-', color='b')
plt.xlabel("Iteration")
plt.ylabel("Objective Function Value (|Y|)")
plt.title("Convergence of Bayesian Optimization")
plt.grid(True)
plt.show()

In [ ]:
# Create partial dependency plots for each variable
fig, axs = plt.subplots(1, 3, figsize=(18, 5))

# Mean values for the other variables
x_means = np.mean(X, axis=0)

for i in range(3):
    # Vary only the i-th variable over its observed range
    x_varied = np.linspace(X[:, i].min(), X[:, i].max(), 100)
    X_plot = np.tile(x_means, (100, 1))  # Start with all features at mean
    X_plot[:, i] = x_varied  # Vary only the i-th feature
    
    # Transform with polynomial features
    X_plot_poly = poly.transform(X_plot)
    
    # Predict output for each value of the i-th variable
    Y_pred = poly_model.predict(X_plot_poly)
    
    # Plot the relationship between the i-th variable and the prediction
    axs[i].plot(x_varied, Y_pred, label=f"Variable {i+1}")
    axs[i].set_xlabel(f"X{i+1}")
    axs[i].set_ylabel("Predicted Y")
    axs[i].set_title(f"Effect of Variable {i+1} on Y (Polynomial)")
    axs[i].grid()

plt.tight_layout()
plt.show()